---
title: "YS SPA Assessment"
author: "Sanika Sule"
date: "`r Sys.Date()`"
output: github_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(tidyr)
library(dplyr)
library(readr)
library(ggplot2)
library(knitr)
library(writexl)
```

```{r load_excel}
youth_info = readxl::read_excel("data/YS SPA Assessment (1).xlsx",  
             sheet = "Youth Info")|>
             janitor::clean_names()
employment_info = readxl::read_excel("data/YS SPA Assessment (1).xlsx",  
             sheet = "Employment Info")|>
             janitor::clean_names()
education_status = readxl::read_excel("data/YS SPA Assessment (1).xlsx",  
             sheet = "Education Status")|>
             janitor::clean_names()
contacts = readxl::read_excel("data/YS SPA Assessment (1).xlsx",  
             sheet = "Contacts")|>
             janitor::clean_names()
```

```{r youth_info_analysis}
youth_info = youth_info |>
  mutate(gs_total_time = as.numeric(difftime(gs_end_dt, gs_start_dt, units = "days") / 365))
#Calculating average time spent enrolled in SLAM
average_gs_total_time = mean(youth_info$gs_total_time, na.rm = TRUE)
print(average_gs_total_time)
```

```{r youth_info_age}
youth_info = youth_info |>
  mutate(dob = as.Date(dob))

# Calculate the age
youth_info = youth_info |>
  mutate(age = as.numeric(difftime(Sys.Date(), dob, units = "days")) / 365)

youth_info = youth_info |>
  mutate(age_group = cut(age, 
                         breaks = c(14, 17, 21, 25, 29, Inf), 
                         labels = c("14-17", "18-21", "22-25", "26-29", "30+"),
                         right = FALSE))

```

Among students who have disenrolled from active coaching, the average time spent in SLAM is 4.90 years.

```{r education_by_year}
youth_info = youth_info |>
  mutate(clt_nbr = as.character(clt_nbr))
education_status <- education_status |>
  mutate(clt_nbr = as.character(clt_nbr))

education_status = education_status |>
  left_join(youth_info |> select(clt_nbr, gs_start_dt), by = "clt_nbr")
names(education_status) = tolower(names(education_status))

# Extracting year from gs_start_date
education_status <- education_status |>
  mutate(gs_start_dt = as.Date(gs_start_dt)) |>
  mutate(start_year = format(gs_start_dt, "%Y"))
```

```{r none_hs_diploma}
# Filter the data for students with "None" under highest_diploma
none_hs_diploma = education_status |>
  filter(highest_diploma == "None")

# Count the occurrences of each current_school_status
none_diploma_status = none_hs_diploma |>
  group_by(current_school_status) |>
  summarise(count = n())

# Calculate the total number of students in the filtered data
total_students = sum(none_diploma_status$count)

# Calculate the percentages for each current_school_status
none_diploma_status = none_diploma_status |>
  mutate(percentage = (count / total_students) * 100)
kable(none_diploma_status)
```

```{r highest_diploma_year}
summary_data = education_status |>
  group_by(start_year, highest_diploma) |>
  summarise(count = n(), .groups = 'drop')

custom_colors = c(
  "Vocational Certificate" = "#F47D73",
  "Unknown" = "#F49A73",
  "None" = "#F8766D",
  "Master's Degree" = "#F4B173",
  "HS Diploma" = "#F9A602",
  "GED" = "#F9629F",
  "Bachelor's Degree" = "#FAA3A3",
  "Associate's Degree" = "#FAA376"
)

# Highest Diploma by Start Year Bar Chart
ggplot(summary_data, aes(x = count, y = highest_diploma, fill = highest_diploma)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ start_year) +
  scale_fill_manual(values = custom_colors) +
  labs(title = "Highest Diploma by SLAM Start Year",
       x = "Count",
       y = "Highest Diploma",
       fill = "Highest Diploma") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom")
```

```{r}
# Calculate the total number of students
total_students = nrow(education_status)

# Calculate the count and percentage of each highest_diploma based on the total number of students
diploma_summary = education_status |>
  group_by(highest_diploma) |>
  summarise(count = n()) |>
  mutate(percentage = (count / total_students) * 100)

# Print the summary data to verify
kable(diploma_summary)
```

```{r employment_length}
# Formatting 'start_dt' and 'end_dt' as dates and converting 8900 to current date
employment_info = employment_info |>
  mutate(end_dt = as.Date(ifelse(end_dt == "8900-12-31", end_dt, Sys.Date()), format = "%Y-%m-%d"))

employment_info = employment_info |>
  mutate(start_dt = as.Date(start_dt, format = "%Y-%m-%d"))

employment_info = employment_info |>
  mutate(employment_time_days = as.numeric(difftime(end_dt, start_dt, units = "days")))

# Average length of employment in years
employment_info |>
  summarise(average_length_years = mean(employment_time_days, na.rm = TRUE) / 365)
```
Among students who report employment during this period, the average length of employment is 1.66 years.

```{r emp_desc_stat}

emp_total = nrow(employment_info)

# employment_level percentage and count calculations
employment_level_summary <- employment_info |>
  group_by(employment_level) |>
  summarise(count = n()) |>
  mutate(percentage = (count / emp_total) * 100)

# employment_level summary data
kable(employment_level_summary)

# outcome_desc percentage and count calculations
outcome_desc_summary <- employment_info |>
  group_by(outcome_desc) |>
  summarise(count = n()) |>
  mutate(percentage = (count / emp_total) * 100)

# outcome_desc summary data
kable(outcome_desc_summary)
```

```{r emp_over_time, warning=FALSE}
employment_info <- employment_info %>%
  mutate(start_dt = as.Date(start_dt, format = "%Y-%m-%d"),
         start_year = year(start_dt))

# Employment initiation yearly counts
yearly_counts <- employment_info |>
  group_by(start_year) |>
  summarise(count = n())

# Employment initiation line graph
ggplot(yearly_counts, aes(x = start_year, y = count)) +
  geom_line() +
  geom_point() +
  geom_text(aes(label = count), vjust = -0.5) + 
  labs(title = "Initiation of Employment Over Time (2019-2023)",
       x = "Year",
       y = "New Student Employment (n)") +
  theme_minimal()
```

```{r}
youth_info = youth_info |>
  mutate(clt_nbr = as.character(clt_nbr))
contacts = contacts |>
  mutate(clt_nbr = as.character(clt_nbr))

# Select coach and supervisor columns
youth_info_selected = youth_info |>
  select(clt_nbr, coach_name, gs_supervisor)

# Merge the contacts sheet with the selected columns from youth_info on clt_nbr
contacts = contacts |>
  left_join(youth_info_selected, by = "clt_nbr")
```

```{r coach_contacts}
# Define "Engaged / Responded" as a successful attempt
success_label = "Engaged / Responded"
unique(contacts$contact_outcome)

# Calculate the percentage of successful attempts by coach_name
coach_contacts = contacts |>
  group_by(coach_name) |>
  summarise(total_attempts = n(),
            successful_attempts = sum(contact_outcome == success_label, na.rm = TRUE),
            success_percentage = (successful_attempts / total_attempts) * 100) |>
  arrange(desc(success_percentage))|>
  rename(`Coach` = coach_name, `Total Attempts` = total_attempts, `Successful Attempts` = successful_attempts, `Success Rate` = success_percentage)

# Print the success table
kable(coach_contacts)

coach_contacts |>
  summarise(average_success_rate = mean(`Success Rate`, na.rm = TRUE))
```

The average contact success rate among all coaches is 70.70%.

```{r coach_plot}
ggplot(coach_contacts, aes(x = reorder(Coach, `Success Rate`), y = `Success Rate`)) +
  geom_point(size = 4, color = "gold") +
  labs(title = "Contact Success Rate by Coach",
       x = "Coach",
       y = "Success Rate (%)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))

```

```{r supervisor_contacts}
supervisor_contacts = contacts |>
  group_by(gs_supervisor) |>
  summarise(total_attempts = n(),
            successful_attempts = sum(contact_outcome == success_label, na.rm = TRUE),
            success_percentage = (successful_attempts / total_attempts) * 100) |>
  arrange(desc(success_percentage))|>
  rename(`GS Supervisor` = gs_supervisor, `Total Attempts` = total_attempts, `Successful Attempts` = successful_attempts, `Success Rate` = success_percentage)

# Print the success table
kable(supervisor_contacts)

```

```{r contacts_time}
contacts = contacts |>
  mutate(contact_event_date = as.Date(contact_event_date, format = "%Y-%m-%d"),
         year_month = format(contact_event_date, "%Y-%m"))

# Define successful and unsuccessful labels
success_label = "Engaged / Responded"
unsuccessful_label = "Attempt / No Response"

# Calculate the number of success and unsuccessful attempts per month by gs_supervisor
monthly_counts = contacts |>
  mutate(outcome_type = case_when(
    contact_outcome == success_label ~ "Successful",
    contact_outcome == unsuccessful_label ~ "Unsuccessful",
    TRUE ~ "Other"
  )) |>
  filter(outcome_type %in% c("Successful", "Unsuccessful")) |>
  group_by(gs_supervisor, year_month, outcome_type) |>
  summarise(count = n(), .groups = 'drop')

# Define custom colors for outcome types
gs_colors = c(
  "Successful" = "#F9A602",  
  "Unsuccessful" = "#F9629F" 
)

# Create the line graph using ggplot2
ggplot(monthly_counts, aes(x = year_month, y = count, color = outcome_type, group = outcome_type)) +
  geom_line() +
  geom_point() +
  facet_wrap(~ gs_supervisor) +
  scale_color_manual(values = gs_colors) +  # Add custom colors
  labs(title = "Contact Attempts Over Time by GS Supervisor (2022-2023)",
       x = "Year-Month",
       y = "Contact Attempts (n)",
       color = "Outcome Type") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

```{r employment_tests}
#Adding age_group variable to employment_info
youth_age = youth_info |>
  select(youth_name, age_group)
employment_info = employment_info |>
  left_join(youth_age, by = "youth_name")
employment_info = employment_info |>
  filter(!is.na(age_group))

# Employment level and age group chi-square test
contingency_table = table(employment_info$age_group, employment_info$employment_level)
chi_square_test = chisq.test(contingency_table)
print(chi_square_test)

# Wage level and age group ANOVA 
anova_result = aov(wage_level ~ age_group, data = employment_info)
print(anova_result)
tukey_result = TukeyHSD(anova_result)
print(tukey_result)
```

```{r wage_age}
hourly_employment <- employment_info |>
  filter(!is.na(wage_level) & wage_type == "per hour")

# Calculate the average wage for each age group
wage_by_age <- hourly_employment |>
  group_by(age_group) |>
  summarise(average_wage = mean(wage_level, na.rm = TRUE))|>
  rename(`Age Group` = age_group, `Hourly Wage` = average_wage)

# Print the results
kable(wage_by_age)
```

